### ISSUE TITLE
🌭 CUPS impresoras persistentes docker-compose

### ISSUE THREAD

**Issue by raulcorado** [pablokbs/peladonerd#100]
Tengo una RaspberryPi3b, raspbian y estoy utilizando docker-compose adjunto el archivo.    El problema es que no me deja persistentes las impresoras en CUPS. En volumes tengo ./printers.conf:/etc/cups/printers.conf y lo que hace es que me crea una carpeta llamada "printers.conf", deberia ser archivo. 
Probe a montar todo el directorio (./cups_conf:/etc/cups) pero no envia los archivos de la carpeta del contenedor cups.
Muy agradecido
[docker-compose.yaml.txt](https://github.com/pablokbs/peladonerd/files/5144735/docker-compose.yaml.txt)

**Comment by pablokbs** [comment]
Yo lo tengo así en una rpi4:

```
  cups:
    image: ydkn/cups
    expose:
      - 631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./cups:/etc/cups
    environment:
      - ADMIN_PASSWORD=xxxxx
    restart: unless-stopped
    privileged: true
    network_mode: host
```

Y me creó el directorio cups con todos los archivos adentro, probá corriendo los siguientes comandos:

```
docker-compose down cups
docker-compose rm -f cups
docker-compose up cups -d
```
