### ISSUE TITLE
a0js/rpi-cups 

### ISSUE THREAD

**Issue by nanock91** [pablokbs/peladonerd#102]
Buenas, estoy intentando montar este docker-compose pero con las mismas lineas que peladonerd no me funciona. Cuando miro en docker ps -a siempre veo que está en restating. Si cambio lo de always por otra cosa se queda en exited, aunque haga un docker start pid no cambia. He probado, incluso, a sacarlo de mi docker-compose original y ponerlo en otro para que tenga el "version 2", pero nada... alguna idea?

Así se quedaría

CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                     PORTS                                                                        NAMES
d3a9ef4cdfcc        a0js/rpi-cups                     "/usr/sbin/cupsd -f"     16 seconds ago      Exited (1) 2 seconds ago                                                                                cups-impresora_cups_1

El docker compose es exactamente el mismo que el del repo y el video de youtube.

**Comment by pablokbs** [comment]
hacé un `docker-compose logs cups` para ver que te dice

**Comment by nanock91** [comment]
> hacé un `docker-compose logs cups` para ver que te dice

Primero gracias por contestar pablo! Me sale esto haciendo eso:

Attaching to cups-impresora_cups_1
cups_1  | standard_init_linux.go:211: exec user process caused "exec format error"

He probado también a instalar cups sin docker, lo levanto y entro en la web, pero a la hora de instalar una impresora no me sale mi modelo tan rápido como a ti. Mi modelo es la brother HL 1100 (prácticamente la misma que la tuya) y lo tengo en un ubuntu server 20.

¿Sabrías a que se puede deber ambas cosas?

Muchas gracias y un saludo!

**Comment by pablokbs** [comment]
`cups_1 | standard_init_linux.go:211: exec user process caused "exec format error"` eso es porque estas usando una imagen que no es para tu arquitectura, pareciera que no lo estás corriendo en una raspberry pi. Si lo estás corriendo en un ubuntu con amd64, podés usar otra imagen.

Ahí [acabo de cambiar](https://github.com/pablokbs/peladonerd/commit/c6aeff4d0819de285dd068dfc45b405f29805163) el docker-compose del repo con una imagen multi plataforma:

```
version: "2"

services:

  cups:
    image: ydkn/cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./cups:/etc/cup
    environment:
      # El user y password por defecto son admin / admin
      - ADMIN_PASSWORD=admin
    restart: always
    privileged: true
```

Fijate si con ese te funciona bien

**Comment by nanock91** [comment]
Gracias pablo por responder!

He probado y ya arranca bien el docker, pero a la hora de acceder a la configuración de administración redirige a la IP del contenedor creo, aparece esto:

Se requiere actualización
Debe acceder a esta página usando el URL https://172.20.0.2:631/admin/.

Aunque lo cambie por mi IP local me vuelve a redirigir ahí. Por el resto de la web si que puedo navegar sin problemas.

**Comment by pablokbs** [comment]
Fijate de ponerlo en modo host, agregale esto al final:

`network_mode: host`

**Comment by nanock91** [comment]
Me muestra las mismas lineas de antes pero cambiando la IP 172.20.0.2 por mi IP de la LAN 192.168.1.150 pero sigue sin funcionar.
Saca errores en el texto que tras hacer click en 2-3 opciones acaba sacando el código HTML:

<!DOCTYPE HTML>
<html>
  <head>
    <link rel="stylesheet" href="/cups.css" type="text/css">
    <link rel="shortcut icon" href="/apple-touch-icon.png" type="image/png">
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=9">
    <meta name="viewport" content="width=device-width">
    <title>Inicio - CUPS 2.2.10</title>
  </head>
  <body>
    <div class="header">
      <ul> [Continua..]

Es raro, porque tengo 7-8 contenedores funcionando bien desde hace meses y nunca me había pasado algo así.

Un saludo pablo!

**Comment by dhcpy** [comment]
Hola Buenas!
Tengo el mismo problemita.. lo instale usando este archivo compose..

al darle "añadir impresoras", sale:

 " Se requiere actualización
Debe acceder a esta página usando el URL https://172.18.0.2:631/admin/."

> `cups_1 | standard_init_linux.go:211: exec user process caused "exec format error"` eso es porque estas usando una imagen que no es para tu arquitectura, pareciera que no lo estás corriendo en una raspberry pi. Si lo estás corriendo en un ubuntu con amd64, podés usar otra imagen.
> 
> Ahí [acabo de cambiar](https://github.com/pablokbs/peladonerd/commit/c6aeff4d0819de285dd068dfc45b405f29805163) el docker-compose del repo con una imagen multi plataforma:
> 
> ```
> version: "2"
> 
> services:
> 
>   cups:
>     image: ydkn/cups
>     ports:
>       - 631:631
>     volumes:
>       - /var/run/dbus:/var/run/dbus
>       - /dev/bus/usb:/dev/bus/usb
>       - ./cups:/etc/cup
>     environment:
>       # El user y password por defecto son admin / admin
>       - ADMIN_PASSWORD=admin
>     restart: always
>     privileged: true
> ```
> 
> Fijate si con ese te funciona bien

**Comment by demavares** [comment]
año 2024 aquí la solución:

```
version: "2.1"
services:
  cups:
    image: ydkn/cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./cups:/etc/cup
    environment:
      # El user y password por defecto son admin / admin
      - ADMIN_PASSWORD=admin
    restart: always
    privileged: true
    network_mode: host
```
