### ISSUE TITLE
rsnapshot-cron error en imagen docker

### ISSUE THREAD

**Issue by Vctrsnts** [pablokbs/peladonerd#103]
Buenas,

Siguiendo tu "**docker-compose.yaml**" respecto al **pablokbs/rsnapshot-cron** cuando lo inicio y visualizo el log "**docker logs -f rsnapshot**" me aparece el siguiente error 

**standard_init_linux.go:211: exec user process caused "exec format error"**

Me da la sensación que la imagen de docker esta creada para otra cpu y no para arm.

Es correcto??

**Comment by pablokbs** [comment]
Acabo de subir una nueva version que tiene las 2 arquitecturas, fijate ahora, vas a tener que bajar de nuevo la imagen: `docker-compose pull rsnapshot && docker-compose up -d`

**Comment by Vctrsnts** [comment]
Buenas,
Siento informar que no funciona.
He hecho lo siguiente :
 - `docker system prune -a` -> para borrar la imagen que tenia
 - `docker-compose up -d rsnapshot`
  -Entonces se ha descargado la ultima imagen que hay :
```
Status: Download newer image for pablokbs/rsnapshot-cron:latest
Creating rsnapshot ... done
```
 - `docker logs -f rsnapshot`
 - Entonces el log que me aparece es el siguiente :
`standart_init_linux.go:211:211 exec user process caused "exec format error"`

Tambien he probado de construir la imagen a traves de `build`, pero tambien me da el mismo error

Ya no se que más mirar.

Gracias y perdon por las molestias

**Comment by pablokbs** [comment]
Donde estás corriendo esto? acabo de correrlo en mi mac (usando docker desktop)


```
$ docker run -it pablokbs/rsnapshot-cron bash
+ set -e
+ '[' bash = rsnapshotd ']'
+ exec bash
bash-4.4# uname -a
Linux dab5ea7e2efa 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux
bash-4.4# rsnapshot -v
rsnapshot 1.4.2
Usage: rsnapshot [-vtxqVD] [-c cfgfile] [command] [args]
Type "rsnapshot help" or "man rsnapshot" for more information.
```

**Comment by Vctrsnts** [comment]
Buenas,

Lo estoy corriendo en un raspberry pi

`Linux wiking 5.4.69-v7l+ #1344 SMP Fri Oct 2 16:01:56 BST 2020 armv7l GNU/Linux`

Perdon por las molestias

**Comment by pablokbs** [comment]
Acá lo corro en una raspberrypi4 y me anda. Podrías probar estos comandos?

```
$ docker run -it pablokbs/rsnapshot-cron bash
+ set -e
+ '[' bash = rsnapshotd ']'
+ exec bash
bash-4.4#
bash-4.4#
bash-4.4# uname -a
Linux 9e7a1ecbb2b5 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
bash-4.4# rsnapshot -v
rsnapshot 1.4.2
Usage: rsnapshot [-vtxqVD] [-c cfgfile] [command] [args]
Type "rsnapshot help" or "man rsnapshot" for more information.
```

**Comment by Vctrsnts** [comment]
De nuevo gracias, pero siento informar que sigue sin funcionar y muestra el mismo error.

He probado los siguientes comandos :

- `docker run -it pablokbs/rsnapshot-cron bash`
- `docker pull pablokbs/rsnapshot-cron:tag`
- `docker-compose con la "versión" tag`

Y en todas obtengo el mismo error. No se que pasa, pero de nuevo, gracias por toda la ayuda...

Investigare a ver que puedo encontrar...

**Comment by pablokbs** [comment]
Cuando corrés `docker run -it pablokbs/rsnapshot-cron bash` te dice exec error?

**Comment by Vctrsnts** [comment]
Buenas.

Si me da el mismo error :

`docker run -it pablokbs/rsnapshot-cron:tag bash`

Le pongo el `tag`, para que coja la ultima versión ( tambien lo he probado sin ponerlo, que entonces me coje `latest` ) y con los 2 me muestra el mismo error :

`standart_init_linux.go:211:211 exec user process caused "exec format error"`

Hay una cosa que me extraña, que el docker en las dos arquitecturas, ocupa lo mismo.

De nuevo gracias por todo....

**Comment by pablokbs** [comment]
No me habia dado cuenta que estaba usando el tag "`tag`" ahí lo acabo de construir de nuevo con latest, y aparte estaba usando el Dockerfile erróneo, en teoría ya arreglé todo (y voy a subir el nuevo Dockerfile al repo) . Lo acabo de probar bien en amd64 y arm

Podrías hacer un `docker pull pablokbs/rsnapshot-cron:latest` y despues `docker run -it --entrypoint /bin/sh pablokbs/rsnapshot-cron` ? Esto es lo que acabo de hacer:

```
$ docker run -it --entrypoint /bin/sh pablokbs/rsnapshot-cron
/ #
/ #
/ # rsnapshot -v
rsnapshot 1.4.3
Usage: rsnapshot [-vtxqVD] [-c cfgfile] [command] [args]
Type "rsnapshot help" or "man rsnapshot" for more information.
```

**Comment by Vctrsnts** [comment]
Buenas

Si ejecuto los siguiente comandos tal como me indicas :
```
docker pull pablokbs/rsnapshot-cron:latest 
docker run -it --entrypoint /bin/sh pablokbs/rsnapshot-cron
```
Me funciona correctamente, pero en cambio, si lo hago a traves de` docker-compose` sigue dando el mismo error. Te pongo mi docker-compose que estoy utilizando :

```
 rsnapshot:
   image: pablokbs/rsnapshot-cron:latest
   container_name: rsnapshot
   restart: always
   volumes:
     - /etc:/host/etc:ro
     - /mnt/config:/host/config:ro
     - /home/pi:/host/home/pi:ro
     - /mnt/seguretat:/snapshot
     - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime 
   environment:
     - BACKUP_DIRECTORIES=/host/        seguretat/
     - CRON_DAILY=0 0 5 * * *
     - CRON_WEEKLY=0 0 6 * * 1
     - CRON_MONTHLY=0 30 6 1 * *
     - RSNAPSHOT_HOURLY_TIMES=0
     - RSNAPSHOT_DAILY_TIMES=7
     - RSNAPSHOT_WEEKLY_TIMES=4
     - RSNAPSHOT_MONTHLY_TIMES=3 
``` 
Porque ya no entiendo nada...
