### ISSUE TITLE
WireGuard y problema con Kernel headers

### ISSUE THREAD

**Issue by elclay7** [pablokbs/peladonerd#117]
He intentado levantar la VPN WireGuard en mi Rasberry PI 4 de 4gb sin éxito...

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armv7l
**Kernel version** Linux 5.4.72-v7l
**Instalación de Docker:** Desde el repo de Raspbian

Este es el **docker-compose.yml** 
```
version: "3.3"
services:
wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - SERVERURL=misite.algo.cl
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /mnt/TOSHIBA/WireGuard/config:/config
      - /mnt/TOSHIBA/WireGuard/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs
```
**** Raspbian kernel naming convention detected, attempting to install raspbian kernel headers ****
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Get:5 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main Sources [96.0 kB]
Get:7 http://archive.raspberrypi.org/debian buster/main armhf Packages [336 kB]
Fetched 465 kB in 7s (69.9 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  raspberrypi-kernel-headers
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 26.3 MB of archives.
After this operation, 171 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20201022-1 [26.3 MB]
Fetched 26.3 MB in 4s (5,845 kB/s)
Selecting previously unselected package raspberrypi-kernel-headers.
(Reading database ... 14046 files and directories currently installed.)
Preparing to unpack .../raspberrypi-kernel-headers_1.20201022-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1.20201022-1) ...
Setting up raspberrypi-kernel-headers (1.20201022-1) ...
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72+
 * dkms: running auto installation service for kernel 5.4.72+            [ OK ] 
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v7+
 * dkms: running auto installation service for kernel 5.4.72-v7+         [ OK ] 
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v7l+
 * dkms: running auto installation service for kernel 5.4.72-v7l+        [ OK ] 
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v8+
 * dkms: running auto installation service for kernel 5.4.72-v8+         [ OK ] 
** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . **
```
¡¡¡** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ** !!!

![image](https://user-images.githubusercontent.com/13406685/99572281-2d403700-29b3-11eb-8e41-93530ac01616.png)

Alguna pista de como arreglar esto... hasta el momento solo he encontrado en la INTERNET este hilo con soluciones medio truchas [link](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/4)
¡Help!
