### ISSUE TITLE
No todos los contenedores inician al reiniciar el server (nginx + letsencrypt +prestashop)

### ISSUE THREAD

**Issue by elclay7** [pablokbs/peladonerd#125]
Hola tengo una duda tal vez bastante tonta pero no logro hacer que todos mis contenedores inicien luego de un reinicio de server, este es mi docker-compose (nginx + letsencrypt +prestashop) ¡IMPRESIONANTE! y luego de un reinicio solo levanta el contenedor de nginx-proxy y  letsencrypt, mariadb y el prestashop NO lo cual rompe mi corazon, alguna idea de porque pasa esto?

```
version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  mariadb:
    image: bitnami/mariadb:10.5.8
    container_name: mariadb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=holamundo

    volumes:
      - ./mariadb:/bitnami/mariadb
      - ./mariadb/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro

  prestashop:
    image: prestashop/prestashop:1.7.7.0-7.3-apache
    container_name: prestashop
    restart: always
    expose:
      - 80
      - 443
    environment:
      - PS_INSTALL_AUTO=0
      - PS_FOLDER_ADMIN=admin
      - PS_ENABLE_SSL=1
      - VIRTUAL_HOST=shop.some.domain
      - LETSENCRYPT_HOST=shop.some.domain
      - LETSENCRYPT_EMAIL=some@mail.com
    volumes:
      - ./prestashop-ldm/html:/var/www/html
      - ./prestashop-ldm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    depends_on:
      - mariadb
```
