### ISSUE TITLE
[Question] Getting exec format error running letsencrypt docker-compose in a pi 4

### ISSUE THREAD

**Issue by txitxo0** [pablokbs/peladonerd#126]
Hola, gracias por los aportes tuyos y de la comunidad.

No estoy seguro de que esto sea un issue o más bien una pregunta. No consigo que letsencrypt me ande. El sitio me funciona con http pero no con https (abiertos los puertos).

Estoy usando duckdns.org y exactamente tu mismo [docker-compose de la rama master ](https://github.com/pablokbs/peladonerd/blob/master/raspi/7/docker-compose.yaml) cambiando volumes y environment de nginx_fredrikson para apuntar a mi web
Sin embargo, el letsencrypt me lanza el siguiente error todo el rato:
`etsencrypt_1       | standard_init_linux.go:219: exec user process caused: exec format error`
El docker compose es:

```
version: '3.5'
services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: duch/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_fredrikson:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /media/storage/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=miweb.duckdns.org
      - LETSENCRYPT_HOST=miweb.duckdns.org
      - LETSENCRYPT_EMAIL=mi@email.com

volumes:
  html:
  vhostd:
  confd:
  certs:

```
Alguna idea, o mejor sitio paracompartir este problema? Gracias!

**Comment by pablokbs** [comment]
Estas corriendo en una raspberry? que version? pareciera que estás usando una imagen que no es compatible con ARM

**Comment by txitxo0** [comment]
> Estas corriendo en una raspberry? que version? pareciera que estás usando una imagen que no es compatible con ARM

Gracias por la pronta respuesta. Perdona, no lo puse en el cuerpo del mensaje. Sí, es una raspberry Pi 4:
```
$>  cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Las imagenes que estoy utilizando, tal cual las del repo en master:
para el proxy: budry/jwilder-nginx-proxy-arm
para letsencrypt: duch/letsencrypt-nginx-proxy-companion:stable
y para nginx: nginx

No se por donde tirar

**Comment by txitxo0** [comment]
Se debió de quedar corrompido algun fichero. Eliminé todo y al regenerar con jrcs/letsencrypt-nginx-proxy-companion ya está funcionando. 
Armando la PR por si es de utilidad a alguien. Gracias

**Comment by txitxo0** [comment]
Hola @pablokbs No conseguí abrir PR a tu rama, no se si no has dejado permisos para ello o simplemente como nunca he trabajado con github (a nivel profesional con otros tantos sí como gitLab, bitbucket, azuredevops....) quizás no haya sabido.
La solución de cambiar el letsenrypt por esta otra imagen: jrcs/letsencrypt-nginx-proxy-companion me sigue funcionando sin problemas, por si te apetece echarle un vistazo ;) 
Gracias por tus videos

```
nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /path/to/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=#hosting domain
      - LETSENCRYPT_HOST=#hosting domain
      - LETSENCRYPT_EMAIL=#email
```
