### ISSUE TITLE
Ayudas varias raspberry docker

### ISSUE THREAD

**Issue by brotwi** [pablokbs/peladonerd#16]
Hola Pablo muchas gracias por tus tutoriales son geniales!, soy muy nuevo en esto de raspberry, pero voy aprendiendo supongo, te consulto lo primero que hice fue instalar el contenedor de pihole, mediante docker compose yml no yaml y funciono perfecto, ahora el inconveniente que me surge es que estoy instalando rtorrent, pero que hago con el puerto 80 que ya lo esta ulilizando pihole? Gracias.
Saludos desde San Juan

**Comment by franrebo84** [comment]
solo tenes que cambiar el puerto en el que vas a exponer el servicio en el archivo docker-compose:

Ahora tenes algo asi:

```
rtorrent:
    image: pablokbs/rutorrent-armhf
    ports:
      - 80:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /home/pi/torrents-config/rtorrent:/config/rtorrent
      - /home/pi/downloads:/downloads
    restart: always
```

Cambialo por :

```
rtorrent:
    image: pablokbs/rutorrent-armhf
    ports:
      - 8080:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /home/pi/torrents-config/rtorrent:/config/rtorrent
      - /home/pi/downloads:/downloads
    restart: always
```

Y ahora apuntale desde el browser a la ip del raspberry asi:

<IP>:8080

Deberia funcionar.

Saludos!
