### ISSUE TITLE
Conflicto de puertos entre nginx y posteio

### ISSUE THREAD

**Issue by RRicardotj** [pablokbs/peladonerd#17]
Saludos Pablo.
Estoy tratando de replicar la configuración del video de posteio en local
pero tengo un conflicto de puertos entre un contenedor de ngnix y posteio
este es mi docker compose
```
version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/public:/srv/www/static
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf
  poste:
    image: analogic/poste.io
    restart: always
    network_mode: "host"
    expose:
      - 25
      - 80
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - /root/mail-data:/data
    environment:
      - HTTPS=ON
```

Debido a que el posteio se encuentra en  `network_mode: "host"` el puerto expuesto `80` entra en conflicto con el puerto mapeado `80` del contenedor `nginx`. No quisiera mapear el puerto del `ngnix` a otro puerto porque lo necesito en ese, pero no se como hacer con el posteio porque necesita exponer el puerto `80` para poder entrar a su UI.

No se como resolver este conflicto o si Docker ofrece una solucion de mapear un puerto expuesto cuando esta en `network_mode: "host"`
