### ISSUE TITLE
duda sobre HPA

### ISSUE THREAD

**Issue by MauricioRyan** [pablokbs/peladonerd#2]
Pablo,
estoy intentando poner mi K8S en producción y usar HPA, lo que me resulta incómodo es que para calcular el límite de escalado (en mi caso CPU) usa lo asignando en resources.requests, y en mi caso que el resuources.limits es más del doble del request, empieza a escalar antes de lo necesario ¿hay alguna forma de cambiarlo para que use como referencia el limit?

**Comment by pablokbs** [comment]
Buenas! Podrias pegar tu config? estas usando `averageUtilization`?

**Comment by MauricioRyan** [comment]
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edna-krabappel
  namespace: beta
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: edna-krabappel
  targetCPUUtilizationPercentage: 80

**Comment by pablokbs** [comment]
Buenas, probá usando `averageUtilization` (esto viene con la version 2 de hpa)

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: edna-krabappel
  namespace: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edna-krabappel
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

Creo que con esto vas a poder jugar un poco mejor con los valores, [acá](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) tenés mas info.
