### ISSUE TITLE
Dominios

### ISSUE THREAD

**Issue by mariooc** [pablokbs/peladonerd#20]
Buenas Pablo,

una consulta, 
Estoy ejecutando pi-hole con (gracias a tu vídeo me anime a usarlo con docker )
me gustaría quiero agregar rtorrent que también va hace el bind 80:80

ahora bien, hay alguna manera utilizando docker para utilizar virtualhost?

**Tipo**
-   hole.rpi
-   rtorrent.rpi
-   cups.rpi

**rpi es solo un ejemplo de TLD**

en un momento imagine que podía  utilizar **jwilder/nginx-proxy**

Igualmente pienso que de debe tocar algo a nivel o router o se podría aprovechar el dns de pihole?

Saludos.

**Comment by franrebo84** [comment]
Podes usar traefik como proxy reverso. Mirate este link 

https://medium.com/@joshuaavalon/setup-traefik-step-by-step-406792afe9b2

**Comment by pablokbs** [comment]
Crear los virtualhost lo podes hacer con jwilder/nginx-proxy (hice un video de eso [acá](https://youtu.be/S2YFqf4L7l8)) ... estuve viendo y parece que no se pueden cargar nuevos hostnames en pi-hole para que resuelva. Pero lo que podes hacer es usar el dhcp que viene integrado:

![image](https://user-images.githubusercontent.com/4028336/62217334-d7d8b480-b380-11e9-85c9-71d05db7e693.png)

Ahi podes agregarle nombres a los hosts y te va a resolver (todos van a apuntar a la ip de la raspberry, pero usando el nombre te va a usar el virtualhost) Sino lo que podes hacer es simplemente agregar esos nombres a tu `/etc/hosts`

**Comment by mariooc** [comment]
Para podes usar el el método de DHCP de la rpi, debo deshabilitar el del router?
el método por `/etc/hosts` debería editarlo en todos los dispositivos en lo que me quiera conectar? 
de ser así:
> peladonerd: no escala.

**Comment by pablokbs** [comment]
Correcto, no escala. Opa, mirá lo que encontré:

https://github.com/pi-hole/pi-hole/pull/1266

```
pi@raspberrypi:~# pihole -a hostrecord home.mydomain.de 192.168.1.10
Setting host record for home.mydomain.de -> 192.168.1.10

pi@raspberrypi:~# grep 'home' /etc/dnsmasq.d/01-pihole.conf
host-record=home.mydomain.de,192.168.1.10

```

Tirando ese comando se te agrega el nombre al dns de pi-hole, probalo y avisame

**Comment by mariooc** [comment]
no me anduvo
me retorna la pagina de Welcome to nginx!

te dejo mi docker-compose

```
version: '2'
services:

  traefik:
    container_name: traefik
    image: traefik:alpine
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock

  pihole:
    container_name: pihole
    restart: unless-stopped
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9080:80/tcp"
      # - "443:443/tcp"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: ${PIHOLE_ADMIN_PASS}
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN

    labels:
      - traefik.enable=true
      - traefik.port=9080
      - "traefik.frontend.rule=Host:hole.rpi.local"

  samba:
    image: dperson/samba:rpi
    container_name: samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime
      - /home/pi/media:/media
      - /home/pi/downloads:/downloads

  rtorrent:
    image: pablokbs/rutorrent-armhf
    container_name: rtorrent
    ports:
      - 9083:80
      - 51413:51413
      - 6881:6881/udp
    expose:
      - "80"
    volumes:
      - /home/pi/torrents-config/rtorrent:/config/rtorrent
      - /home/pi/downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.port=9083
      - "traefik.frontend.rule=Host:rtorrent.docker.localhost"
    restart: always
```

lo agregue como me dijiste:


```
pi@rpi:~ $ docker exec -it pihole  grep docker /etc/dnsmasq.d/01-pihole.conf
host-record=rtorrent.docker.localhost,10.0.0.2
host-record=hole.docker.localhost,10.0.0.2
```
- traefik.port=9083 y con 80 
pero no pasaba nada
