### ISSUE TITLE
[Bug] Los certificados SSL no persisten con el contenedor de letsencrypt

### ISSUE THREAD

**Issue by varaskkar** [pablokbs/peladonerd#244]
**¿Donde pasa?** ➜ En todos los ficheros yml de docker compose que contengan el contenedor de LetsEncrypt
**¿Qué pasa?** ➜ Crea el certificado pero cuando reinicias el contenedor vuelve a crearlo sin comprobar si ya existe
**¿Solución?** ➜ Crear un volumen para guardar el certificado

[Bug ya solucionado en stackoverflow](https://stackoverflow.com/questions/66102225/jrcs-letsencrypt-nginx-proxy-companion-docker-image-too-many-certificates-alr) 

En resumen, la solución es agregar la linea `- acme:/etc/acme.sh` en la sección volumes de `letsencrypt` y `nginx-proxy` , y luego agregar `acme:` en la sección volumes de final del fichero.

Saludos.

**Comment by varaskkar** [comment]
Agrego un `docker-compose.yml` que yo uso ya arreglado.

**Nginx + SSL**

```
version: '3'
services:
    www:
        image: nginx
        restart: always
        expose:
            - "80"
        volumes:
            - ./www:/usr/share/nginx/html:ro
        environment:
            - VIRTUAL_HOST=bookscrazy.com,www.bookscrazy.com
            - LETSENCRYPT_HOST=bookscrazy.com,www.bookscrazy.com
            - LETSENCRYPT_EMAIL=felipe@bookscrazy.com
        depends_on:
            - nginx-proxy
            - letsencrypt
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:ro
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - acme:/etc/acme.sh
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - acme:/etc/acme.sh
volumes:
    certs:
    html:
    vhostd:
    acme:
```
