### ISSUE TITLE
Wordpres + MySQL - Variables php.ini + Volumen wp-content

### ISSUE THREAD

**Issue by ChristianBarrientos** [pablokbs/peladonerd#47]
Hola, alguien sabe como puedo pasar una parametrizacion a la configuracion de php (/etc/php.x/apache/php.ini) al momendo de deployment del wordpres? 
COmo seria:
post_max_size=32M;
upload_max_filesize=128M; 
memory_limit=128M;

Tambien, alguien pudo hacer que la wp-content no se pierda? Osea si, se realiza un volumen, pero despues como le digo al deployment del wordpres para que apunte a ese volumen? 
GRacias

**Comment by pablokbs** [comment]
Hola, lo que podés hacer es crear un `php.ini` con esos parametros y montarlo en `/usr/local/etc/php/conf.d/php.ini`

Algo así:

```
  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.2.2-php7.3-apache
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wp_misitio
    volumes:
      - ./wp-data:/var/www/html
      - ./php-conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql:mysql
```

Y ahi mismo te puse el volumen como ejemplo. Igualmente lo mejor es que todo lo que vaya en wp-content tiene que ir en la imagen, o sea, no deberia cambiar cuando está corriendo en producción,, lo metes cuando desarrollás y después lo subís metido en la imagen. Si tenés archivos (por ejemplo imagenes de un blog post) deberias usar un plugin que guarde esas imagenes en algún lugar externo. Por ejemplo S3:

https://wordpress.org/plugins/amazon-s3-and-cloudfront/
