### ISSUE TITLE
probar whoami con ssl

### ISSUE THREAD

**Issue by jandrop** [pablokbs/peladonerd#56]
Estoy probando a usar let's encrypt como has enseñado en los videos con el contenedor de whoami pero me da un error el certificado ssl por http si funciona pero por https me da un error de certificado, alguna idea? 

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: containous/whoami
    restart: always
    environment:
     VIRTUAL_HOST: www.cawaii.com,cawai.com
     LETSENCRYPT_HOST: cawai.com
volumes: 
  certs:
  html:
  vhostd:
```

![image](https://user-images.githubusercontent.com/8020875/76443002-0c562980-63c2-11ea-8a44-e1b0da1fdbe4.png)
![image](https://user-images.githubusercontent.com/8020875/76443057-209a2680-63c2-11ea-8841-212422c859a9.png)

**Comment by fede-r1c0** [comment]
Creo que te falta la variable LETSENCRYPT_EMAIL

**Comment by fede-r1c0** [comment]
> Creo que te falta la variable LETSENCRYPT_EMAIL
Ej: 

    environment:
      - VIRTUAL_HOST=pepito.tech,www.pepito.tech
      - LETSENCRYPT_HOST=pepito.tech,www.pepito.tech
      - LETSENCRYPT_EMAIL=mail@pepito.tech

**Comment by jandrop** [comment]
> > Creo que te falta la variable LETSENCRYPT_EMAIL
> > Ej:
> 
> ```
> environment:
>   - VIRTUAL_HOST=pepito.tech,www.pepito.tech
>   - LETSENCRYPT_HOST=pepito.tech,www.pepito.tech
>   - LETSENCRYPT_EMAIL=mail@pepito.tech
> ```

La he puesto pero sigue igual

**Comment by fede-r1c0** [comment]
expusiste los puertos en whoami? (nunca lo use, no se si es necesario)

Pero te dejo un ejemplo de un contenedor nginx *Dentro de nginx-proxy y con letsencrypt companion):

```
www:
    container_name: nginx-www
    image: nginx
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - /home/pepito/docker-pepito/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pepito.tech,www.pepito.tech
      - LETSENCRYPT_HOST=pepito.tech,www.pepito.tech
      - LETSENCRYPT_EMAIL=pepito@pepito.tech
```
