### ISSUE TITLE
directorios propiedad de root

### ISSUE THREAD

**Issue by jandrop** [pablokbs/peladonerd#57]
Estoy haciendo pruebas con transmission usando la config del docker-compose y mapeando el directorio a un disco usb conectado a la raspberry o sin disco siempre me crea los directorios y ficheros con el propietario root, he intentado usar el campo user: 1000:1000 pero no funciona.  

Alguien me puede ayudar? o no hay forma de solucionarlo y es así?

mi docker-compose.yalm es el siguiente:

```
services:
  transmission:
    command: transmission-daemon -f -g /config
    container_name: transmission
    expose:
    - 9091
    image: jaymoulin/transmission
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    volumes:
    - '/media/usb/docker/torrent/transmission/config:/config'
    - '/media/usb/docker/torrent/downloads:/downloads'
    restart: unless-stopped
    user: 1000:1000
version: "3.3"
```

```
drwxr-xr-x 2 root root 4.0K Mar 12 22:36 blocklists
-rw------- 1 root root  352 Mar 12 22:47 dht.dat
drwxr-xr-x 2 root root 4.0K Mar 12 22:36 resume
-rw------- 1 root root 2.2K Mar 12 22:47 settings.json
drwxr-xr-x 2 root root 4.0K Mar 12 22:36 torrents
```
