### ISSUE TITLE
Docker Wordpress con Macvlan

### ISSUE THREAD

**Issue by ReactionCode** [pablokbs/peladonerd#61]
Hola Pablo.

Muchas gracias por tu curso de Docker y compartir tus conocimientos de maestro ninja con todos!

Después de ver el capitulo de wordpress y de networking he intentado hacer correr wordpress desde una IP en vez de un puerto 8080 pero me ha sido imposible.

Cuando reviso la red creada por docker veo las IP's correctamente asignadas a cada contendedor, pero si hago un ping a la IP es unreachable.

Por lo que entiendo la red macvlan crea una interfaz virtual que debería ser descubrible por toda la red ¿no?

Te paso mi docker-compose.yml a ver si me puedes iluminar y decir donde estoy metiendo la pata.

La Ip de mi portátil es: 192.168.1.131
La interfaz wifi es: wlp1s0

```
version: '3.1'

services:

  wordpress:
    image: wordpress:php7.1-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql
    networks:
       myvlan:
        ipv4_address: 192.168.1.51

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
       myvlan:
        ipv4_address: 192.168.1.50

networks:
  myvlan:
    driver: macvlan
    driver_opts:
      parent: wlp1s0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
```
Muchas gracias.
