### ISSUE TITLE
Problem with  kubernetes/5/metrics/metrics-server-deployment.yaml

### ISSUE THREAD

**Issue by PeterMcGor** [pablokbs/peladonerd#71]
Buenas @pablokbs, 

Estoy mirando tus tutoriales en parte para montar algo que necesito y en parte para enseñarles a algunos colegas, espero que no te importe. 

No estoy muy seguro a que se debe pero con la configuración inicial kubernetes no era capaz de encontrar las las medidas de performance de los nodos, obteniéndose: 

`kubectl top node minikube --> Error from server (NotFound): nodemetrics.metrics.k8s.io "minikube" not found`

`kubectl get all --> horizontalpodautoscaler.autoscaling/php-apache   Deployment/php-apache   <unknown>/50%   1         10        3          15m`

Usando Google lo que finalmente me ha funcionado es modificar "metrics-server-deployment.yaml", como sigue: 

```
containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.1
        imagePullPolicy: Always
       # From here the new staff
        command:
        - /metrics
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
 
```

Lo dejo por aquí por si a alguien le fuese de ayuda. 

Un saludo y gracias por los vídeos!
