### ISSUE TITLE
rsnapshot no me funciona

### ISSUE THREAD

**Issue by eucciferri** [pablokbs/peladonerd#81]
Hola, Pablo! Cómo andás? 
Estuve tratando de configurar rsnapshot pero no funciona.
Al tratar de ejecutar el bash me arroja lo siguiente:
![image](https://user-images.githubusercontent.com/38674416/83936916-a7cb2080-a79e-11ea-9454-545b05097a72.png)

Y en el log me arroja el siguiente error:
![image](https://user-images.githubusercontent.com/38674416/83936849-ce3c8c00-a79d-11ea-9b89-85695a4a487d.png)

Mi configuración del docker-compose es la siguiente:
`rsnapshot:
    container_name: rsnapshot
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - /etc:/host/etc:ro
      - /var-ext/mysql:/host/mysql:ro
      - /var-ext/rsnapshot/backups/testing-docker:/snapshots
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/     snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3`

Muchísimas gracias!!
Abrazo.

**Comment by eucciferri** [comment]
rsnapshot:
    container_name: rsnapshot
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - /etc:/host/etc:ro
      - /var-ext/mysql:/host/mysql:ro
      - /var-ext/rsnapshot/backups/testing-docker:/snapshots
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/     snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3

**Comment by eucciferri** [comment]
Pablo!! Cómo andás??
Estoy usando amd64, específicamente instalé Ubuntu en una Intel NUC (tiene un Celeron) y me puse a aprender con tus videos de docker (aprovecho para felicitarte, sos un genio!).
Ahí especifiqué la imagen con el tag amd64, pero me sigue diciendo lo mismo, es como que no puede levantar el contenedor, se queda en "restarting":

![image](https://user-images.githubusercontent.com/38674416/84464671-88733e00-ac4b-11ea-890a-2c1d12e908dc.png)

**Comment by pablokbs** [comment]
El logs te muestra el mismo error?

**Comment by eucciferri** [comment]
No, en el logs me muestra lo siguiente:

![Captura de Pantalla 2020-06-12 a la(s) 18 10 09](https://user-images.githubusercontent.com/38674416/84547259-8bb50b00-acd9-11ea-9b66-149bbcae2a4c.png)

Probé cambiando en el docker compose la línea "- RSNAPSHOT_HOURLY_TIMES=0" con valor 1,  y ahora el logs me muestra:

![image](https://user-images.githubusercontent.com/38674416/84547504-14cc4200-acda-11ea-9b96-b2b7d755efc2.png)

Y luego de iniciar en docker ps lo muestra como "Restarting".

**Comment by pablokbs** [comment]
Muy raro, que arquitectura estas corriendo? hacé un `uname -a` en el host?

**Comment by eucciferri** [comment]
Te paso el print:

![image](https://user-images.githubusercontent.com/38674416/84579562-1151bd00-ada5-11ea-878e-284bff36a905.png)

**Comment by pablokbs** [comment]
Acabo de correr este compose en Mac (usando docker desktop, que levanta una VM de linux en amd64) y me anduvo bien:

```
version: '3.7'

services:
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: always
    environment:
      - BACKUP_DIRECTORIES=/host/ snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=1
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

La unica diferencia es que no usé ningun volumen, podrias probar levantar este compose en tu maquina?

**Comment by eucciferri** [comment]
(millón de gracias por el seguimiento que le estás haciendo y dedicando a esto, Pablo!!)

Probé recién ese docker-compose y me funcionó bien en mi Mac, no me dio ningún error y hasta pude ejecutar el bash y ver los logs.

Lo raro es que también lo ejecuté en la Intel NUC donde venía haciendo las pruebas y me sigue dando error (incluso le reinstalé desde 0 el Ubuntu Server que tenía corriendo ahí por las dudas). Es rarísimo que no funcione en la NUC.

**Comment by tho7o** [comment]
Muy buenas chicos... También estoy teniendo problemas con este docker-compose, Este es mi código:
`version: '3.7'

services:
  rsnapshot:
    image: pablokbs/rsnapshot-cron:amd64 #si no se especifica amd64 baja versión arm
    restart: on-failure #para que pare al primer fallo y no quede reiniciandose
    volumes:
      - ../Proxy/1/var/www/html/data:/carpeta/
    environment:
      - BACKUP_DIRECTORIES=/carpeta/ snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=2 #Falla con 0 y con 1
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3`

El contenedor no queda estable arriba. Se reinicia cada 20 segundos aprox. por ello le puse "restart: on-failure"

En los logs no muestra nada, ya que se reinicia antes de mostrar cualquier cosa.

**Comment by pablokbs** [comment]
Si haces `docker-compose logs rsnapshot` no te muestra nada?

**Comment by tho7o** [comment]
No Pablo, no muestra nada;
* seteado con restart: on-failure
```
Attaching to rsnap_rsnapshot_1
rsnap_rsnapshot_1 exited with code 0
```
* seteado con restart: unless-stopped;
```Attaching to rsnap_rsnapshot_1 
```
Estoy con UBUNTU 20, Arquitectura x64. Tengo varios contenedores corriendo pero este me está dando ese problema. parace algo en la imagen amd64.

¿Tienes algo como probanrlo?

**Comment by pablokbs** [comment]
Ok, es verdad que latest tiene solo arm (por lo que hay que especificar amd64 si queres usar esa arquitectura)

```
  rsnapshot:
    image: pablokbs/rsnapshot-cron:amd64
    restart: always
    environment:
      - BACKUP_DIRECTORIES=/host/ snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=1
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

Corrí eso en un server ubuntu:

```
# uname -a
Linux fredrikson 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Y me tira este error: 

```
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot hourly
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 254:
ERROR: backup /host/ snapshots/ - Source directory "/host/" doesn't exist
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
```

Que es esperable ya que no monté el volumen, podrias probar con ese compose?

**Comment by tho7o** [comment]
Corriendo el mismo compose que mencionas arriba, me suelta el esperado error de volumen. Montando el volumen en el compose, no me suelta error y pero se reinicia constantemente. Por esto mismo, tampoco me da mucho tiempo dentro del container vía "docker exec rsnapshot -it /bin/bash", porque reinicia y me bota a los pocos segundos. 

Intenta montarle el volumen al compose que me sugieres arriba y miramos si también se reincia en tu server.

**Comment by pablokbs** [comment]
Ok descubrí el problema, la imagen de amd64 estaba apuntando a cualquier imagen, una imagen sin cron, por eso no te andaba nada cuando iniciaba. 

Lo acabo de arreglar y ya están bien subidas (latest tiene las 2 arquitecturas) ... asi que cambien sus docker-compose para que apunten a latest y hagan:

`docker-compose pull rsnapshot && docker-compose up -d` 

Lo tengo corriendo en un server con amd64 con el siguiente docker-compose y anda bien:

```
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - ./host:/host
    command:
      - sleep
      - 1d
    environment:
      - BACKUP_DIRECTORIES=/host/       snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

Noten que  `BACKUP_DIRECTORIES=/host/       snapshots/` tiene un TAB entre `/hosts/` y `snapshots/` .. es muy importante que sea un TAB y no un ESPACIO. No es joda

Prueben de nuevo y avisen @tho7o @eucciferri

**Comment by tho7o** [comment]
Estaba esperando tu respuesta, muchas gracias Pablo.

 Solo como info, los .yml no aceptan TAB. Así que los compose hay que correrlos con espacio. (https://stackoverflow.com/questions/19975954/a-yaml-file-cannot-contain-tabs-as-indentation)

Lo pruebo y te comento.

**Comment by pablokbs** [comment]
Los yaml no pueden tener tabs como identación para cada linea, pero yo hablo de un tab dentro del valor de la variable de entorno, esos si andan.

**Comment by tho7o** [comment]
Like a CHARM! ahora sí está andando. Consulta;
¿Para qué es esto?
```
 command:
      - sleep
      - 1d
```

**Comment by pablokbs** [comment]
Ah eso sacalo :D fue una prueba que estaba haciendo, sacale el command, quedaría así:

```
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - ./host:/host
    environment:
      - BACKUP_DIRECTORIES=/host/       snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```
