### ISSUE TITLE
SSL docker-compose para dos containers Front y Back

### ISSUE THREAD

**Issue by jorgebee65** [pablokbs/peladonerd#82]
Cual sería la mejor forma de levantar una aplicación de SpringBoot + NuxtJS, actualmente lo hago con un docker-compose y funciona perfectamente PERO ahora que estoy intentando agregar SSL lo he logrado para Nuxt usando Nginx Proxy como en tu video (https://www.youtube.com/watch?v=S2YFqf4L7l8) pero ahora las peticiones de mi sitio hacia la API rest no funcionan porque al parecer el API rest no es SSL me está tirando este mensaje:

_"The page at 'https://midominio.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://IP_DROPLET:8585/api/auth/signin'. This request has been blocked; the content must be served over HTTPS"_ 

Me queda claro que tengo que hacer que ahora el API rest tambien acepte peticiones sobre https, lo que no se es si el certificado en el Nginx Proxy me puede servir para ambos containers o tendria que hacer otro para la API rest? 

Este es mi docker-compose, agradezco tus comentarios. Te felicito por los videos me han ayudado a aprender. Saludos

```
version: "3"
  
services:
  view:
    image: jorgebee65/trebol-view:latest
    container_name: view
    depends_on:
      - core
    ports:
      - '5000:5000'
    environment:
      - VIRTUAL_HOST=mitrebolsitio.com 
      - LETSENCRYPT_HOST=mitrebolsitio.com
      - LETSENCRYPT_EMAIL=jorgebee65@hotmail.com
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    networks:
      default:
        aliases:
          - frontview
  core:
    image: jorgebee65/trebol-core:10
    container_name: core
    environment:
      - SPRINGPROFILES=actuator
      - APP_ALLOW_ORIGIN1=http://mitrebolsitio.com
      - APP_ALLOW_ORIGIN2=https://mitrebolsitio.com
      - SERVER_PORT=8585
      - AMAZON_ENDPOINT=https://s3.us-east-1.amazonaws.com
      - AMAZON_BUCKETNAME=mybucketname
      - SPRING_DATA_MONGODB_DATABASE=mrlonches
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=changodb
      - APP_JWTEXPIRATION=86400000
      - APP_NOTIFICATIONS_ENABLE=true
      - APP_JWTSECRET=APP_JWTSECRET
      - AMAZON_ACCESSKEY=AMAZON_ACCESSKEY
      - AMAZON_SECRETKEY=AMAZON_SECRETKEY
    depends_on:
      - changodb
    ports:
      - "8585:8585"
    networks:
      default:
        aliases:
          - restapi
  changodb:
    image: mongo:4.0.8
    container_name: changodb
    ports:
      - "27017:27017"
    networks:
      default:
        aliases:
          - changodb
    volumes:
      - mogo-volume:/data/db

  nginx:
    image: jwilder/nginx-proxy
    restart: always
    container_name: proxy
    depends_on:
      - view
      - core
    ports:
      - '80:80'
      - '443:443'
      - '8585:8585'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      default:
        aliases:
          - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsenc
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      default:
        aliases:
          - lets

volumes:
  certs:
  vhost:
  html:
  mogo-volume:

networks:
  otrared:
```

**Comment by jorgebee65** [comment]
Gracias por tus comentarios, al final investigué que en SpringBoot se puede habilitar la parte de SSL añadiendo un certificado y me fui por ese camino, ahora el REST API acepta peticiones HTTPS y en el proyecto de Vue ahora en vez de apuntar a una IP mando los requests hacia el dominio en el puerto 8443 (https://mitrebolsitio.com:8443). Quedó así el docker-compose:
```
version: "3"
  
services:
  view:
    image: jorgebee65/trebol-view:dominiossl
    container_name: view
    depends_on:
      - core
    ports:
      - '5000:5000'
    environment:
      - VIRTUAL_HOST=mitrebolsitio.com 
      - LETSENCRYPT_HOST=mitrebolsitio.com
      - LETSENCRYPT_EMAIL=jorgebee65@hotmail.com
      - SSL_POLICY=AWS-TLS-1-2-2017-01
    networks:
      default:
        aliases:
          - frontview
  core:
    image: jorgebee65/trebol-core:11
    container_name: core
    environment:
      - SPRINGPROFILES=actuator
      - APP_ALLOW_ORIGIN1=https://mitrebolsitio.com
      - APP_ALLOW_ORIGIN2=http://localhost:3000
      - SERVER_PORT=8443
      - SERVER_SSL_key-store=/tmp/keystore.p12
      - SERVER_SSL_key-store-password=xxxxxxxxxxxxxx
      - AMAZON_ENDPOINT=https://s3.us-east-1.amazonaws.com
      - AMAZON_BUCKETNAME=xxxxxxxxxxxxxx
      - SPRING_DATA_MONGODB_DATABASE=mrlonches
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=changodb
      - APP_JWTEXPIRATION=86400000
      - APP_NOTIFICATIONS_ENABLE=true
      - APP_NOTIFICATIONS_GMAIL_USER=jorgebee65@gmail.com
      - APP_NOTIFICATIONS_GMAIL_PASSWORD=xxxxxxxxxxxxxx
      - APP_JWTSECRET=xxxxxxxxxxxxxx
      - AMAZON_ACCESSKEY=xxxxxxxxxxxxxx
      - AMAZON_SECRETKEY=xxxxxxxxxxxxxx
    depends_on:
      - changodb
    ports:
      - "8443:8443"
    networks:
      default:
        aliases:
          - restapi
  changodb:
    image: mongo:4.0.8
    container_name: changodb
    ports:
      - "27017:27017"
    networks:
      default:
        aliases:
          - changodb
    volumes:
      - mogo-volume:/data/db

  nginx:
    image: jwilder/nginx-proxy
    restart: always
    container_name: proxy
    depends_on:
      - view
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      default:
        aliases:
          - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsenc
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      default:
        aliases:
          - lets

volumes:
  certs:
  vhost:
  html:
  mogo-volume:

networks:
  otrared:
```
Muchas gracias, y sigo aprendiendo con tus videos. Saludos desde México.
