### ISSUE TITLE
nginx-proxy + letsencript + duckdns.org

### ISSUE THREAD

**Issue by moracabanas** [pablokbs/peladonerd#84]
Buenas Pelado, le meto horas a configurar un docker-compose para servir una web que apunta a mi casa y quiero hacerlo de forma segura con SSL. Utilizo duckdns porque es gratis y no sé mucho de cómo https utiliza el SSL pero tengo un conocimiento básico del uso de claves publicas y privadas.

 Sigo tu tu [vídeo](https://www.youtube.com/watch?v=S2YFqf4L7l8). 

Pasos que he seguido:
Primero expongo el puerto 80 de mi nginx solo en la red interna de docker todo va sin SSL para probar que el dominio que tengo en duckdns resuelve a mi direccion IP y llega al proxy. Para ello he redirigido el puerto 80 externo al 80 interno en mi router para la ip de mi host. 
Todo funciona ok puedo llegar a mi web desde el navegador en mi dominio duckdns.

Ahora sigo todos los pasos del vídeo y modifico mi docker-compose con letsencript y queda de la siguiente manera (utilizo imagenes para ARM, y bindmounts locales para ver mejor lo que pasa con los datos, espero sea claro)

``` 
version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=www.docker-iot.duckdns.org,docker-iot.duckdns.org,192.168.1.18
      - LETSENCRYPT_HOST=www.docker-iot.duckdns.org,docker-iot.duckdns.org,192.168.1.18
      - LETSENCRYPT_EMAIL=mimalditomail@mail.com
```

Un curl -I me devuelve que se ha actualizado a https pero la pagina no carga.
He metido mi ip local (192.168.1.18) como virtual host y puedo llegar a ella por https pero no por https. 

No sé cómo saber que está pasando y solucionarlo, me parece una ruta demasiado compleja. 

El certificado que se genera con letsencript me debería de funcionar? cómo sabe "la web" que es seguro?

cien millones de preguntas pero lo básico es que llevo pegado mas de 24h sin avanzar. Mil gracias

**Comment by pablokbs** [comment]
Primero que nada no deberias usar tu ip como virtual_host, usá siempre tu dominio. Lo que podés hacer para probarlo localmente es agregarlo a tu archivo hosts.

Cuando decis que "no llega por https" a que te referis? que error te sale?

saludos

**Comment by moracabanas** [comment]
ok dejo el `VIRTUAL_HOST` sólo con el dominio que tengo.

update del docker-compose.yml:

```
version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=www.docker-iot.duckdns.org,docker-iot.duckdns.org
      - LETSENCRYPT_HOST=www.docker-iot.duckdns.org,docker-iot.duckdns.org
      - LETSENCRYPT_EMAIL=mimail@email.com
```
El problema con el https que no me expliqué correctamente es el siguiente:

hago un `curl -I docker-iot.duckdns.com` respuesta:

```
HTTP/1.1 301 Moved Permanently
Server: nginx/1.13.9
Date: Thu, 11 Jun 2020 14:44:44 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://docker-iot.duckdns.org/
```
respuesta de `nginx-proxy`:

```
nginx-proxy_1  | nginx.1     | docker-iot.duckdns.org 2.154.33.131 - - [11/Jun/2020:14:46:00 +0000] "HEAD / HTTP/1.1" 301 0 "-" "curl/7.55.1"
```

Ahora ingreso `docker-iot.duckdns.org` en el navegador y no se carga nada, la consola del docker-compose no muestra movimiento ni si quiera `nginx-proxy` muestra mensaje y en la consola del navegador obtengo esto 
![image](https://user-images.githubusercontent.com/4382333/84401372-7c638e00-ac03-11ea-8713-85af21108722.png)
