### ISSUE TITLE
letsencrypt con nginx-proxy no genera certificado

### ISSUE THREAD

**Issue by alexlndn** [pablokbs/peladonerd#85]
Hola, que tal, estoy intentando hacer funcionar esta configuración que vi en uno de los videos y la verdad llevo horas revisandolo y no doy con el error, esto está montado en un droplet de digital ocean

docker-compose.yaml
```
version: '3'

services:

    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /root/certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

    letsencrypt:
        container_name: letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        depends_on:
            - nginx-proxy
        volumes:
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /root/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro

    alexaguirre:
        container_name: alexaguirre
        image: node_server
        restart: always
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=alexaguirre.com.ar
            - LETSENCRYPT_HOST=alexaguirre.com.ar,www.alexaguirre.com.ar
            - LETSENCRYPT_EMAIL=alex08lta@gmail.com
volumes:
    vhost:
    html:
```
Salida del log del contenedor de letsencrypt:

2020-06-15 01:10:26,325:INFO:simp_le:1450: Generating new certificate private key
2020-06-15 01:10:30,117:ERROR:simp_le:1417: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5244253360
Challenge validation has failed, see error log.
