### ISSUE TITLE
rsnapshots no genera copias dentro de carpeta snapshots

### ISSUE THREAD

**Issue by tho7o** [pablokbs/peladonerd#87]
Pablo,
Sorry por reabrir el hilo pero creo que tenemos fallos todavía. El container está andando sin errores, pero veo que no está generando los "hourly" dentro de la carpeta "snapshot" del contenedor.

ARCH: amd64
OS: ubuntu 20
IMAGEN: pablokbs/rsnapshot-cron

Los logs que me tira son los siguientes:
```
Attaching to rsnapshot
rsnapshot    | + set -e
rsnapshot    | + '[' rsnapshotd = rsnapshotd ']'
rsnapshot    | + source /usr/bin/rsnapshot.d/rsnapshot.sh
rsnapshot    | ++ set -e
rsnapshot    | ++ cp /usr/bin/rsnapshot.d/rsnapshot.conf /etc/rsnapshot.conf
rsnapshot    | ++ hourly_times=4
rsnapshot    | ++ '[' -n 0 ']'
rsnapshot    | ++ hourly_times=0
rsnapshot    | ++ '[' 0 -gt 0 ']'
rsnapshot    | ++ daily_times=7
rsnapshot    | ++ '[' -n 7 ']'
rsnapshot    | ++ daily_times=7
rsnapshot    | ++ '[' 7 -gt 0 ']'
rsnapshot    | ++ echo -e 'retain\tdaily\t7'
rsnapshot    | ++ weekly_times=4
rsnapshot    | ++ '[' -n 4 ']'
rsnapshot    | ++ weekly_times=4
rsnapshot    | ++ '[' 4 -gt 0 ']'
rsnapshot    | ++ echo -e 'retain\tweekly\t4'
rsnapshot    | ++ monthly_times=12
rsnapshot    | ++ '[' -n 3 ']'
rsnapshot    | ++ monthly_times=3
rsnapshot    | ++ '[' 3 -gt 0 ']'
rsnapshot    | ++ echo -e 'retain\tmonthly\t3'
rsnapshot    | ++ syslogger_conf_tag=
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | ++ syslogger_conf_command=
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | ++ backup_interval=hourly
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | ++ backup_dirs=
rsnapshot    | ++ '[' -n '/backups/       snapshots/' ']'
rsnapshot    | ++ backup_dirs='/backups/       snapshots/'
rsnapshot    | ++ SAVEIFS='
rsnapshot    | '
rsnapshot    | ++ IFS=';'
rsnapshot    | ++ for dir in $backup_dirs
rsnapshot    | +++ sed -e 's/ [ ]*/\t/g'
rsnapshot    | ++ tab_dir='/backups/    snapshots/'
rsnapshot    | ++ echo -e 'backup\t/backups/    snapshots/'
rsnapshot    | ++ IFS='
rsnapshot    | '
rsnapshot    | ++ '[' -n '' ']'
rsnapshot    | + cron_rsnapshot_hourly='0 20 * * * *'
rsnapshot    | + '[' -n '' ']'
rsnapshot    | + cron_rsnapshot_daily='0 30 1 * * *'
rsnapshot    | + '[' -n '0 0 3 * * *' ']'
rsnapshot    | + cron_rsnapshot_daily='0 0 3 * * *'
rsnapshot    | + cron_rsnapshot_weekly='0 40 2 * * 5'
rsnapshot    | + '[' -n '0 0 4 * * 1' ']'
rsnapshot    | + cron_rsnapshot_weekly='0 0 4 * * 1'
rsnapshot    | + cron_rsnapshot_monthly='0 50 4 1 * *'
rsnapshot    | + '[' -n '0 30 5 1 * *' ']'
rsnapshot    | + cron_rsnapshot_monthly='0 30 5 1 * *'
rsnapshot    | + configfile=/root/.jobber
rsnapshot    | + '[' '!' -f /root/.jobber ']'
rsnapshot    | + touch /root/.jobber
rsnapshot    | + cat
rsnapshot    | + '[' 0 -gt 0 ']'
rsnapshot    | + '[' 7 -gt 0 ']'
rsnapshot    | + cat
rsnapshot    | + '[' 4 -gt 0 ']'
rsnapshot    | + cat
rsnapshot    | + '[' 3 -gt 0 ']'
rsnapshot    | + cat
rsnapshot    | + cat /root/.jobber
rsnapshot    | ---
rsnapshot    | - name: Daily
rsnapshot    |   cmd: /usr/bin/rsnapshot daily
rsnapshot    |   time: '0 0 3 * * *'
rsnapshot    |   onError: Continue
rsnapshot    |   notifyOnError: false
rsnapshot    |   notifyOnFailure: false
rsnapshot    |
rsnapshot    | - name: Weekly
rsnapshot    |   cmd: /usr/bin/rsnapshot weekly
rsnapshot    |   time: '0 0 4 * * 1'
rsnapshot    |   onError: Continue
rsnapshot    |   notifyOnError: false
rsnapshot    |   notifyOnFailure: false
rsnapshot    | + exec jobberd
rsnapshot    |
rsnapshot    | - name: Monthly
rsnapshot    |   cmd: /usr/bin/rsnapshot monthly
rsnapshot    |   time: '0 30 5 1 * *'
rsnapshot    |   onError: Continue
rsnapshot    |   notifyOnError: false
rsnapshot    |   notifyOnFailure: false
rsnapshot    |
rsnapshot    | Launching.
rsnapshot    | Loaded 3 new jobs for root.
rsnapshot    | Loaded 0 new jobs for bin.
rsnapshot    | Loaded 0 new jobs for daemon.
rsnapshot    | Loaded 0 new jobs for adm.
rsnapshot    | Loaded 0 new jobs for lp.
rsnapshot    | Loaded 0 new jobs for sync.
rsnapshot    | Loaded 0 new jobs for shutdown.
rsnapshot    | Loaded 0 new jobs for halt.
rsnapshot    | Loaded 0 new jobs for mail.
rsnapshot    | Loaded 0 new jobs for news.
rsnapshot    | Loaded 0 new jobs for uucp.
rsnapshot    | Loaded 0 new jobs for operator.
rsnapshot    | Loaded 0 new jobs for man.
rsnapshot    | Loaded 0 new jobs for postmaster.
rsnapshot    | Loaded 0 new jobs for cron.
rsnapshot    | Loaded 0 new jobs for ftp.
rsnapshot    | Failed to load jobs for open /dev/null/.jobber: not a directory: sshd
rsnapshot    | Loaded 0 new jobs for at.
rsnapshot    | Loaded 0 new jobs for squid.
rsnapshot    | Loaded 0 new jobs for xfs.
rsnapshot    | Loaded 0 new jobs for games.
rsnapshot    | Loaded 0 new jobs for postgres.
rsnapshot    | Loaded 0 new jobs for cyrus.
rsnapshot    | Loaded 0 new jobs for vpopmail.
rsnapshot    | Loaded 0 new jobs for ntp.
rsnapshot    | Loaded 0 new jobs for smmsp.
rsnapshot    | Failed to load jobs for open /dev/null/.jobber: not a directory: guest
rsnapshot    | Loaded 0 new jobs for nobody.
rsnapshot    | Loaded 0 new jobs for jobber_client.
rsnapshot    | New context: 0.0
rsnapshot    | Main thread context: 0.0
rsnapshot    | totalJobs: 1; len(m.jobs): 3
rsnapshot    | New context: 0.0.0
```

Mi compose es:
```
version: '3.7'
services:
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    container_name: rsnapshot
    restart: unless-stopped
    volumes:
      - ./backups:/backups
    environment:
      - BACKUP_DIRECTORIES=/backups/       snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

**Comment by pablokbs** [comment]
No te genera el hourly porque tenes el hourly en 0 en el compose, te metiste al contenedor a mirar el config?

**Comment by tho7o** [comment]
Cambié a "hourly=1" pero sigue sin generarme snaps. Esto lo verifico dentro del container, no me está creando el backup internamente. Los logs son exactamente iguales a los que te comenté arriba. Estoy usando este compose de prueba para ir acorralando el error pero comienzo a creer que está dentro de la imagen. ¿Lo podrías probar?

```
version: '3.7'
services:
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    container_name: rsnapshot
    restart: unless-stopped
    environment:
      - BACKUP_DIRECTORIES=/home/       snapshots/
      - CRON_DAILY=0 0 3 * * *
      - CRON_WEEKLY=0 0 4 * * 1
      - CRON_MONTHLY=0 30 5 1 * *
      - RSNAPSHOT_HOURLY_TIMES=1
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

**Comment by pablokbs** [comment]
Fíjate de entrar al contenedor y ver si están configurados los hourly 

—
Pablo Fredrikson

**Comment by tho7o** [comment]
Esto es lo que tengo dentro del contenedor en rsnapshot.con. El hourly está a 1
```
# RSYNC.SAMBA.ORG
#backup rsync://rsync.samba.org/rsyncftp/       rsync.samba.org/rsyncftp/
retain  hourly  1
retain  daily   7
retain  weekly  4
retain  monthly 3
backup  /home/  snapshots/
```

¿Qué más podría revisar?

**Comment by pablokbs** [comment]
Probá correrlo a mano con `rsnapshot -t hourly` a ver que te dice

**Comment by tho7o** [comment]
Suelta este error Pablo:

‘’’
bash-4.4# rsnapshot -t hourly
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -t hourly
----------------------------------------------------------------------------
ERROR: Can not have first backup level's retention count set to 1, and have a second backup level
‘’’

**Comment by tho7o** [comment]
Hola Pablo;
Tiene que haber algo mal en la imagen. Ya he probado todo y no logro hacerlo andar en amd64 con ubuntu 20.

**Comment by pablokbs** [comment]
El primer error está bien, te dice que no podes guardar un solo "hourly" y despues tener otro nivel de backups.

El segundo anduvo bien tambien, no te tiró error. HOURLY=2 significa que va a hacer un backup por hora, y va a guardar un historial de 2.

**Comment by tho7o** [comment]
Vale vale, pero con HOURLY=2 aún así no me genera los backup dentro de la carpera "snapshots"

**Comment by pablokbs** [comment]
Si haces un `tree /snapshots/` que te sale?

**Comment by tho7o** [comment]
Dentro del contenedor el comando "tree" no es válido (no está instalado). Pero dentro de "/snapshots" no hay nada. A tí este compose te corre?

**Comment by pablokbs** [comment]
No lo tengo con hourly, te paso mi compose que estoy usando en una raspberry:

```
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: unless-stopped
    volumes:
      - /etc:/host/etc:ro
      - /home/kbs:/host/home/kbs:ro
      - /mnt/storage/wd/backup/raspberrypi:/snapshots
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/      raspberrypi/
      - CRON_DAILY=0 0 5 * * *
      - CRON_WEEKLY=0 0 6 * * 1
      - CRON_MONTHLY=0 30 6 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

Y este es el contenido de mi directorio con backups en el host:

```
root@raspi4:/mnt/storage/wd/backup/raspberrypi# ls -alh
total 56K
drwxr-xr-x 14 root root 4.0K Jun 22 10:00 .
drwx------  4 root root 4.0K Mar 18 21:34 ..
drwxr-xr-x  3 root root 4.0K Jun 22 09:00 daily.0
drwxr-xr-x  3 root root 4.0K Jun 21 09:00 daily.1
drwxr-xr-x  3 root root 4.0K Jun 20 09:00 daily.2
drwxr-xr-x  3 root root 4.0K Jun 19 09:00 daily.3
drwxr-xr-x  3 root root 4.0K Jun 18 09:00 daily.4
drwxr-xr-x  3 root root 4.0K Jun 17 09:00 daily.5
drwxr-xr-x  3 root root 4.0K May 12 09:00 monthly.0
drwxr-xr-x  3 root root 4.0K Mar 31 09:00 monthly.1
drwxr-xr-x  3 root root 4.0K Jun 16 09:00 weekly.0
drwxr-xr-x  3 root root 4.0K Jun  9 09:00 weekly.1
drwxr-xr-x  3 root root 4.0K Jun  2 09:00 weekly.2
drwxr-xr-x  3 root root 4.0K May 25 09:00 weekly.3
```

**Comment by tho7o** [comment]
Sí, es el mismo que está en el repo. Pero que va, esa imagen para amd64 no anda, te lo aseguro. Solo anda para ARM, parece.

**Comment by pablokbs** [comment]
Lo acabo de poner en mi server amd64 en digital ocean, lo voy a dejar unos dias y te aviso, pero lo corrí a mano una vez y el backup se generó bien, mismo compose

```
  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: unless-stopped
    volumes:
      - /etc:/host/etc:ro
      - /home/kbs:/host/home/kbs:ro
      - /backups:/snapshots
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/      digitalocean/
      - CRON_DAILY=0 0 5 * * *
      - CRON_WEEKLY=0 0 6 * * 1
      - CRON_MONTHLY=0 30 6 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

Probaste corriendolo a mano? `rsnapshot daily` ? El `-t` es solo para testear que esté todo bien, pero no hace el backup

![image](https://user-images.githubusercontent.com/4028336/85406492-49d95f80-b538-11ea-8ba1-8b36de774079.png)
