### ISSUE TITLE
rsnapshot - exec user process caused "exec format error" en arquitectura armhf

### ISSUE THREAD

**Issue by locuraskyline** [pablokbs/peladonerd#95]
Buenas tardes,

Me esta pasando [esto](https://github.com/pablokbs/peladonerd/issues/81) mismo con la diferencia que yo estoy con arquitectura armhf

Comparto mi docker-compose por si ven algo atípico.

```
rsnapshot:
    image: pablokbs/rsnapshot-cron:latest
    container_name: rsnapshot
    restart: always
    volumes:
      - /etc:/host/etc:ro
      - /home/rubio:/host/home/rubio:ro
      - /mnt/storage/backups/snapshots:/snapshots
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/       raspberrypi/
      - CRON_DAILY=0 0 5 * * *
      - CRON_WEEKLY=0 0 6 * * 1
      - CRON_MONTHLY=0 30 6 1 * *
      - RSNAPSHOT_HOURLY_TIMES=1
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
```

Gracias
