### ISSUE TITLE
Sevidor funcionando con NGINX agregar poste io

### ISSUE THREAD

**Issue by fedeaguilera** [pablokbs/peladonerd#97]
Hola pelado, muchismas gracias por tus videos. Tengo una consulta tengo un app en node corriendo en digital ocean con un servidor Nginx funcionando como proxy. Es posible agregarle poste io para tener mi servidor de correo en el mismo lugar. A que puertos tendria que dirigir el proxy del nginx corriendo en el serivdor? Gracias saludos

**Comment by pablokbs** [comment]
Hola, podes usar algo como [este ejemplo](https://github.com/pablokbs/peladonerd/blob/master/varios/1/docker-compose.yaml) reemplazando el servicio de www con poste. Yo estoy usando algo asi en mi server:

```
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mail:
    image: analogic/poste.io:2.2.1
    restart: unless-stopped
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    expose:
      - "80"
      - "443"
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime:ro
      - /root/docker/mail-data:/data
      - /root/docker/mail/etc/spamassassin/local.cf:/etc/spamassassin/local.cf
      - /root/docker/volumes/html/.well-known:/opt/www/.well-known
    environment:
      - HTTPS=OFF
      - VIRTUAL_HOST=mail.ejemplo.com
      - LETSENCRYPT_HOST=mail.ejemplo.com
      - LETSENCRYPT_EMAIL=pablo@ejemplo.com

volumes:
  certs:
  html:
    driver: local-persist
    driver_opts:
      mountpoint: /root/docker/volumes/html
  vhostd:
  confd:
```

**Comment by luistriana28** [comment]
@pablokbs 

Gracias pelado por tu video. Yo tengo poste corriendo normal. Pero en mi conf de nginx, no he podido lograr que un cliente se conecte usando los puertos 25, 110, 993 etc.

Tengo nginx por cada docker ya que tengo varios servicios.

Podrás ayudarme?

**Comment by pablokbs** [comment]
Te recomiendo que abras un nuevo issue con tu config y los errores que ves asi te podemos ayudar

**Comment by DavidGarrido** [comment]
Buenas tardes, tengo la siguiente configuracion 
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./data:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=email.libercol.com
      - LETSENCRYPT_HOST=email.libercol.com
      - LETSENCRYPT_EMAIL=admin@libercol.com
    depends_on:
      - nginx-proxy
      - letsencrypt
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
  libercol:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - VIRTUAL_HOST=libercol.com,www.libercol.com
      - LETSENCRYPT_HOST=libercol.com,www.libercol.com
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
      - nginx-proxy
      - letsencrypt
    #ports:
      #- 80:3000
    expose:
      - "3000"
    volumes:
      - ./libercol:/app
  poste:
    image: analogic/poste.io
    restart: always
    network_mode: "host"
    expose:
      - 25
      - 8080
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - ./poste-data:/data
    environment:
      - HTTPS=ON
      - VIRTUAL_HOST=poste.libercol.com
      - LETSENCRYPT_HOST=poste.libercol.com
    depends_on:
      - nginx_proxy
      - letsencrypt
volumes: 
  certs:
  html:
  vhostd:

pero no me funciona el posteio, necesito ayuda Gracias

**Comment by DavidGarrido** [comment]
buenas tardes tengo la siguiente conf pero no me funciona posteio ayudaaa


version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./data:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=email.libercol.com
      - LETSENCRYPT_HOST=email.libercol.com
      - LETSENCRYPT_EMAIL=admin@libercol.com
    depends_on:
      - nginx-proxy
      - letsencrypt
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
  libercol:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - VIRTUAL_HOST=libercol.com,www.libercol.com
      - LETSENCRYPT_HOST=libercol.com,www.libercol.com
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
      - nginx-proxy
      - letsencrypt
    #ports:
      #- 80:3000
    expose:
      - "3000"
    volumes:
      - ./libercol:/app
  poste:
    image: analogic/poste.io
    restart: always
    network_mode: "host"
    expose:
      - 25
      - 8080
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - ./poste-data:/data
    environment:
      - HTTPS=ON
      - VIRTUAL_HOST=poste.libercol.com
      - LETSENCRYPT_HOST=poste.libercol.com
    depends_on:
      - nginx_proxy
      - letsencrypt
volumes: 
  certs:
  html:
  vhostd:`
`

**Comment by DavidGarrido** [comment]
tengo los dominios funcionando por si quieren entrar a verificar y darme una mano.

**Comment by danielbaldovino** [comment]
Hola hola, alguién siguió trabajando en esto?, tengo el mismo problema. 

Uso Nginx Proxy manager y no puedo hacer que ande Poste.

Intenté o que Pablo mencionó arriba, así como esto sin éxito: https://www.cloudrocket.at/posts/self-hosted-mail-server-with-poste.io-and-nginx/

> Hola, podes usar algo como [este ejemplo](https://github.com/pablokbs/peladonerd/blob/master/varios/1/docker-compose.yaml) reemplazando el servicio de www con poste. Yo estoy usando algo asi en mi server:
> 
> ```
>   nginx-proxy:
>     image: jwilder/nginx-proxy:0.6.0
>     restart: unless-stopped
>     ports:
>       - "80:80"
>       - "443:443"
>     volumes:
>       - /var/run/docker.sock:/tmp/docker.sock:ro
>       - certs:/etc/nginx/certs:ro
>       - confd:/etc/nginx/conf.d
>       - vhostd:/etc/nginx/vhost.d
>       - html:/usr/share/nginx/html
>     labels:
>       - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
> 
>   letsencrypt:
>     image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
>     restart: unless-stopped
>     volumes:
>       - certs:/etc/nginx/certs:rw
>       - confd:/etc/nginx/conf.d
>       - vhostd:/etc/nginx/vhost.d
>       - html:/usr/share/nginx/html
>       - /var/run/docker.sock:/var/run/docker.sock:ro
> 
>   mail:
>     image: analogic/poste.io:2.2.1
>     restart: unless-stopped
>     ports:
>       - "25:25"
>       - "110:110"
>       - "143:143"
>       - "465:465"
>       - "587:587"
>       - "993:993"
>       - "995:995"
>     expose:
>       - "80"
>       - "443"
>     volumes:
>       - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime:ro
>       - /root/docker/mail-data:/data
>       - /root/docker/mail/etc/spamassassin/local.cf:/etc/spamassassin/local.cf
>       - /root/docker/volumes/html/.well-known:/opt/www/.well-known
>     environment:
>       - HTTPS=OFF
>       - VIRTUAL_HOST=mail.ejemplo.com
>       - LETSENCRYPT_HOST=mail.ejemplo.com
>       - LETSENCRYPT_EMAIL=pablo@ejemplo.com
> 
> volumes:
>   certs:
>   html:
>     driver: local-persist
>     driver_opts:
>       mountpoint: /root/docker/volumes/html
>   vhostd:
>   confd:
> ```

**Comment by fedeaguilera** [comment]
> poste.libercol.com

Hola @DavidGarrido pudiste hacerlo funcionar. Yo probe una configuracion parecida a la tuya con una app en react y tampoco me funciona. Pudiste encontrar solucion?

**Comment by danielbaldovino** [comment]
Hola @fedeaguilera, parcialmente.

Al final hice algunos ajustes para hacerlo correr con la red en modo bridge y logré hacer que cargara, recibir correos  y enviar algunos correos. Al correo empresarial nunca pudo enviar correos, supongo que porque tenía problemas con los registros DNS y lo dejé en stand-by porque tenía otros proyectos urgentes.

Te comparto los dos docker-compose que use (uno para el proxy manager y otro para poste):

POSTE

services:
  poste:
    container_name: poste
    image: analogic/poste.io:latest
    restart: always
    hostname: mail.{hostname}.com
    #network_mode: bridge
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    expose:
      - "80"
      - "443"
    environment:
      - HTTPS=OFF
      #- HTTPS_PORT=5443
      #- HTTP_PORT=5080
      #- TZ=America/Bogota
      - VIRTUAL_HOST=webmail.{hostname}.com
      - LETSENCRYPT_HOST=webmail.{hostname}.com
      - LETSENCRYPT_EMAIL={mymail}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./proxy/letsencrypt/live/npm-1/privkey.pem:/data/ssl/server.key:ro
      - ./proxy/letsencrypt/live/npm-1/chain.pem:/data/ssl/ca.crt:ro
      - ./proxy/letsencrypt/live/npm-1/cert.pem:/data/ssl/server.crt:ro
      - ./data:/data
    networks:
      wm_network:
        aliases:
         - wm_net
networks:
 wm_network:
  name: {NETWORK1}
  driver: bridge

PROXY MANAGER

version: '3.7'
services:
  proxy_manager:
    container_name: proxy_manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '{external_port}:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "proxy_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "{MSQL_USER}"
      DB_MYSQL_PASSWORD: "{MSQL_PWD}"
      DB_MYSQL_NAME: "{DBNAME}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      proxy_network:
        aliases:
         - proxy_net
  proxy_db:
    container_name: proxy_db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '{MSQL_ROOT_PWD}'
      MYSQL_DATABASE: '{DB}'
      MYSQL_USER: '{DB_USR}'
      MYSQL_PASSWORD: 'MSQL_PWD'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      proxy_network:
        aliases:
         - proxydb_net
networks:
 proxy_network:
  name: {NETWORK1}
  driver: bridge

![image](https://user-images.githubusercontent.com/98127885/151875817-76320d8f-ce76-45de-89a9-afd7c0e40fcd.png)


![image](https://user-images.githubusercontent.com/98127885/151875982-4643a0fa-32c2-4749-ab72-5c9f4d14a752.png)

**Comment by DavidGarrido** [comment]
Hola, la verdad que no pude hacerlo funcionar y hable con el provehedor de mi vps para que me hiciera la instalacion del webuzo que ya trae configurado un servidor web y uno de mail

**Comment by juampymdd** [comment]
Buenas disculpen la demora pero pude hacerlo funcionar de la siguiente manera. Tengo la web y el webmail en el mismo droplet. Creo que eso es lo que querían lograr.

Saludos

```

version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    container_name: miweb
    expose:
      - "80"
    volumes:
      - /home/miweb:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=miweb.com,www.miweb.com
      - LETSENCRYPT_HOST=miweb.com,www.miweb.com
      - LETSENCRYPT_EMAIL=admin@miweb.com
    depends_on:
      - nginx-proxy
      - letsencrypt
  
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - VIRTUAL_HOST=email.miwb.com, www.email.miweb.com
      - LETSENCRYPT_EMAIL=info@miweb.com
      - LETSENCRYPT_HOST=email.miweb.com
      - HTTPS=OFF
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/nginx/html/.well-known:/opt/www/.well-known
      - /home/mail-data:/data
volumes: 
  certs:
  html:
  vhostd:

```
